argos/urls.py
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.urls import path
from django.views.generic import TemplateView
from rest_framework.authtoken import views as drf_views
from . import views

app_name = "argos"

editionName = settings.APP_CONFIG['edition'].lower()

urlpatterns = [
    # URLs específicas do aplicativo web
    # home: /
    path('', views.home, name = 'home'),
    # dash: /dash
    path('dash/', views.dash, name = 'dash'),
    # devlist: /devlist
    path('devlist/', views.devlist, name = 'devlist'),
    # filterDate: /filterDate
    path('filterDate/', views.filterDate, name = 'filterDate'),
    # detail: /<eui>/detail
    path('<eui>/detail/', views.detail, name = 'detail'),
    # geomap: /<gateway_id>/geomap
    path('<gateway_id>/geomap/', views.geomap, name = 'geomap'),

    # URL para chamada de página de Tarifa Branca
    path('whitetarifflist/', views.whitetarifflist, name='whitetarifflist'),
    path('<mac>/whitetariff/', views.whitetariff, name='whitetariff'),

    # accounts: URLs específicas para autenticação de usuário
    path('accounts/login/', auth_views.LoginView.as_view(template_name='registration/' + editionName + '/login.html'), name='login'),
    path('accounts/logout/', auth_views.LogoutView.as_view(template_name='registration/' + editionName + '/logged_out.html'), name='logout'),
    path('accounts/password_reset/', auth_views.PasswordResetView.as_view(template_name='registration/' + editionName + '/password_reset_form.html'), name='password_reset'),
    path('accounts/password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='registration/' + editionName + '/password_reset_done.html'), name='password_reset_done'),
    path('accounts/reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/' + editionName + '/password_reset_complete.html'), name='password_reset_complete'),
    path('accounts/reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='registration/' + editionName + '/password_reset_confirm.html'), name='password_reset_confirm'),

    # registration: URLs específicas para criação de conta de usuário
    path('registration/account-activation/<uidb64>/<token>/', views.account_activation, name='account_activation'),
    path('registration/account-registration/', views.account_registration, name='account_registration'),
    path('registration/activation-complete', TemplateView.as_view(template_name='registration/' + editionName + '/activation_complete.html'), name='activation_complete'),
    path('registration/new-user/', views.newUser, name = 'newUser'),
    path('registration/registration-complete/', TemplateView.as_view(template_name='registration/' + editionName + '/registration_complete.html'), name='registration_complete'),
    path('registration/signup/', TemplateView.as_view(template_name='registration/' + editionName + '/signup_form.html'), name='signup'),
    path('registration/token-auth/', drf_views.obtain_auth_token),
    path('registration/user/<username>/', views.get_user),

    # rest: URLs específicas da REST API
    # card: /rest/card/<installation_code>
    path('rest/card/<installation_code>/', views.cards_usedby_installation_code),
    # installation: /rest/installation/<installation_code>
    path('rest/installation/<installation_code>/', views.installation_exists),
    # loadprofile: /rest/loadprofile/<installation_code>
    path('rest/loadprofile/<installation_code>/', views.loadprofile),
    # transaction: /rest/transaction/credit
    path('rest/transaction/credit/', views.credit),
    # transaction: /rest/transaction/emergency_credit
    path('rest/transaction/emergency_credit/',  views.emergency_credit),
    # transaction: /rest/transaction/<installation_code>
    path('rest/transaction/<installation_code>/', views.transactions_from_installation_code),

    # Flutter database view
    path('rest/mappoints/', views.mapPoints),
]

argos/templates/argos/icaro/fixedbottombar.html
{% load static %}

<div class="container">
  <div class="row" >
    <div class="col-sm">
      <img class="d-block mx-auto" src="{% static 'img/icaro/daimon.png' %}" alt="Logo Daimon" style="margin-top:20px;margin-bottom:20px">
    </div>
    <div class="col-sm">
      <img class="d-block mx-auto" src="{% static 'img/icaro/aneel.png' %}" alt="Logo Annel" style="margin-top:20px;margin-bottom:20px">
    </div>
    <div class="col-sm"> 
      <img class="d-block mx-auto" src="{% static 'img/icaro/centrum.png' %}" alt="Logo Centrum" style="margin-top:20px;margin-bottom:20px">
    </div>
  </div>
</div>

argos/templates/argos/icaro/fixedtopbar.html
{% load i18n admin_urls %}
{% load static %}

<nav class="navbar navbar-expand-sm navbar-shadow fixed-top bg-white d-flex" style="padding-top: 3px; padding-bottom: 4px;">

  <img src="{% static 'img/icaro/icaro.png' %}" width="32" height="32" alt="icaro" style="padding-bottom: 6px;">
  <span class="navbar-text text-muted" style="width:60px; margin-left:20px">ÍCARO</span>

  <a class="nav-link navtop-link" href={% url 'argos:home' %}>Home</a>
  {% if request.user.is_authenticated %}
    <a class="nav-link navtop-link" href={% url 'icaro-admin:argos_installation_changelist' %}>Instalações</a>
    <a class="nav-link navtop-link" href={% url 'icaro-admin:argos_httpdevice_changelist' %}>Medidores</a>
    <a class="nav-link navtop-link" href={% url 'logout' %}>Logout</a>
  {% else %}
    <a class="nav-link navtop-link" href={% url 'login' %}>Login</a>
    <a class="nav-link navtop-link" href={% url 'argos:signup' %}>Signup</a>
  {% endif %}

  <img src="{% static 'img/icaro/celesc.png' %}" class="ml-auto" alt="Logo Celesc">

</nav>

argos/templates/argos/icaro/header.html
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="description" content="Sistema de Supervisão para IoT">
<meta name="author" content="Daimon">
<meta name="keywords" content="Argonauta,IoT,LoRa,LoRaWAN">

<title>Ícaro</title>

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">

<!-- Favicon -->
<link rel="shortcut icon" href="{% static 'img/icaro/favicon.ico' %}" /> <!-- Internet Explorer -->
<link rel="icon" href="{% static 'img/icaro/favicon.ico' %}" type="image/x-icon" /> <!-- Outros Browsers -->

<style>
  .dropdown-toggle {
    color: dimgray;
    padding: .3rem;
    padding-bottom: 0;
  }
  .dropdown-toggle:hover {
    color: black;
  }
  .dropdown-item {
    color: dodgerblue;
    padding-left: 1rem;
  }
  .dropdown-item:hover {
    border-radius: 7px;
    background: #b9bbbe;
    color: black;
  }
  .navtop-link:hover {
    border-radius: 7px;
    background-color:#FDB813;
    color: white;
  }
  .navbar-shadow {
    box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
  }

  #app-buttons-div{
    margin-left: 5em;
    margin-right: 5em;
    padding:5em
  }
  #app-buttons-div button{
    border:1px solid #E0EBF7;
    width: 200px;
    height: 200px;
  }
  #app-buttons-div button:hover{
    background-color: orange;
  }
  #app-buttons-div button p{
    font-size:20px;
    margin-top: 30px;
  }
  #app-buttons-div button img {
    margin-top: 10px;
    width: 60px;
    height: 60px;
  }
</style>

argos/templates/argos/icaro/home.html
<!doctype html>
<html lang="pt-BR">
  <head>
    {% load static %}
    {% include "argos/icaro/header.html" %}
  </head>
  <body>
    {% include "argos/icaro/fixedtopbar.html" %}
    <!--<div>Ícones feitos por <a href="https://www.flaticon.com/br/autores/dinosoftlabs" title="DinosoftLabs">DinosoftLabs</a> from <a href="https://www.flaticon.com/br/" title="Flaticon">www.flaticon.com</a></div>-->
    <!--<div>Ícones feitos por <a href="https://www.freepik.com" title="Freepik">Freepik</a> from <a href="https://www.flaticon.com/br/" title="Flaticon">www.flaticon.com</a></div>-->
    <!--<div>Ícones feitos por <a href="https://www.freepik.com" title="Freepik">Freepik</a> from <a href="https://www.flaticon.com/br/" title="Flaticon">www.flaticon.com</a></div>-->
    <!--<div>Ícones feitos por <a href="https://www.flaticon.com/br/autores/iconixar" title="iconixar">iconixar</a> from <a href="https://www.flaticon.com/br/" title="Flaticon">www.flaticon.com</a></div>-->
    {% if request.user.is_authenticated %}
      <!-- Botoes na Tela Principal -->
      <div class="container-fluid" style="margin-top:4em">
        <div class="d-flex justify-content-center flex-wrap" id="app-buttons-div">

          <a href="">
            <button type="button" class="btn  btn-outline-primary">
              <img src="{% static 'img/icaro/voltimetro.png' %}">
              <p>Medições</p>
            </button>
          </a>

          <a href="">
            <button type="button" class="btn  btn-outline-primary">
              <img src="{% static 'img/icaro/grafico-de-linha.png' %}" style="margin-top: 30px;">
              <p>Campanha de Medidas</p>
            </button>
          </a>

          <a href={% url 'argos:whitetarifflist' %}>
            <button type="button" class="btn  btn-outline-primary">
              <img src="{% static 'img/icaro/conta.png' %}">
              <p>Tarifa Branca</p>
            </button>
          </a>

          <a href="">
            <button type="button" class="btn  btn-outline-primary">
              <img src="{% static 'img/icaro/classe-energetica.png' %}" style="margin-top: 30px;">
              <p>Eficiência Energética</p>
            </button>
          </a>

        </div>
      </div>
    {% else %}
      <!-- Início do carrossel -->
      <div id="myCarousel" class="carousel slide" data-ride="carousel" style="margin-top:58px;height=100%">
    
        <!-- Wrapper for slides -->
        <div class="carousel-inner">
          <div class="carousel-item active">
            <img class="d-block w-100" src="{% static 'img/icaro/banner.jpg' %}" alt="Primeiro Slide">
            <div class="carousel-caption d-none d-md-block">
              <h1>ÍCARO</h1>
              <h4>A plataforma de medidores da CELESC</h4>
            </div>
          </div>
        </div>
      </div>
      <!-- Fim do carrossel -->
    {% endif %}

    {% include "argos/icaro/fixedbottombar.html" %}

    <script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>

  </body>
</html>

argos/templates/argos/icaro/whitetariff.html
{% extends "argos/whitetariffinner.html" %}

{% block header %}
    {% include "argos/icaro/header.html" %}
{% endblock %}

{% block fixedtopbar %}
    {% include "argos/icaro/fixedtopbar.html" %}
{% endblock %}

{% block fixedbottombar %}
  {% include "argos/icaro/fixedbottombar.html" %}
{% endblock %}

argos/templates/argos/icaro/whitetarifflist.html
{% extends "argos/whitetarifflistinner.html" %}

{% block header %}
    {% include "argos/icaro/header.html" %}
{% endblock %}

{% block fixedtopbar %}
    {% include "argos/icaro/fixedtopbar.html" %}
{% endblock %}

{% block fixedbottombar %}
  {% include "argos/icaro/fixedbottombar.html" %}
{% endblock %}