argos/urls.py
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.urls import path
from django.views.generic import TemplateView
from rest_framework.authtoken import views as drf_views
from . import views

app_name = "argos"

editionName = settings.APP_CONFIG['edition'].lower()

urlpatterns = [
    # URLs específicas do aplicativo web
    # home: /
    path('', views.home, name = 'home'),
    # dash: /dash
    path('dash/', views.dash, name = 'dash'),
    # devlist: /devlist
    path('devlist/', views.devlist, name = 'devlist'),
    # filterDate: /filterDate
    path('filterDate/', views.filterDate, name = 'filterDate'),
    # detail: /<eui>/detail
    path('<eui>/detail/', views.detail, name = 'detail'),
    # geomap: /<gateway_id>/geomap
    path('<gateway_id>/geomap/', views.geomap, name = 'geomap'),

    # URL para chamada de página de Tarifa Branca
    path('whitetarifflist/', views.whitetarifflist, name='whitetarifflist'),
    path('<mac>/whitetariff/', views.whitetariff, name='whitetariff'),

    # accounts: URLs específicas para autenticação de usuário
    path('accounts/login/', auth_views.LoginView.as_view(template_name='registration/' + editionName + '/login.html'), name='login'),
    path('accounts/logout/', auth_views.LogoutView.as_view(template_name='registration/' + editionName + '/logged_out.html'), name='logout'),
    path('accounts/password_reset/', auth_views.PasswordResetView.as_view(template_name='registration/' + editionName + '/password_reset_form.html'), name='password_reset'),
    path('accounts/password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='registration/' + editionName + '/password_reset_done.html'), name='password_reset_done'),
    path('accounts/reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/' + editionName + '/password_reset_complete.html'), name='password_reset_complete'),
    path('accounts/reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='registration/' + editionName + '/password_reset_confirm.html'), name='password_reset_confirm'),

    # registration: URLs específicas para criação de conta de usuário
    path('registration/account-activation/<uidb64>/<token>/', views.account_activation, name='account_activation'),
    path('registration/account-registration/', views.account_registration, name='account_registration'),
    path('registration/activation-complete', TemplateView.as_view(template_name='registration/' + editionName + '/activation_complete.html'), name='activation_complete'),
    path('registration/new-user/', views.newUser, name = 'newUser'),
    path('registration/registration-complete/', TemplateView.as_view(template_name='registration/' + editionName + '/registration_complete.html'), name='registration_complete'),
    path('registration/signup/', TemplateView.as_view(template_name='registration/' + editionName + '/signup_form.html'), name='signup'),
    path('registration/token-auth/', drf_views.obtain_auth_token),
    path('registration/user/<username>/', views.get_user),

    # rest: URLs específicas da REST API
    # card: /rest/card/<installation_code>
    path('rest/card/<installation_code>/', views.cards_usedby_installation_code),
    # installation: /rest/installation/<installation_code>
    path('rest/installation/<installation_code>/', views.installation_exists),
    # loadprofile: /rest/loadprofile/<installation_code>
    path('rest/loadprofile/<installation_code>/', views.loadprofile),
    # transaction: /rest/transaction/credit
    path('rest/transaction/credit/', views.credit),
    # transaction: /rest/transaction/emergency_credit
    path('rest/transaction/emergency_credit/',  views.emergency_credit),
    # transaction: /rest/transaction/<installation_code>
    path('rest/transaction/<installation_code>/', views.transactions_from_installation_code),

    # Flutter database view
    path('rest/mappoints/', views.mapPoints),
]

argos/templates/argos/dashinner.html
<!doctype html>
<html lang="pt-BR">
  <head>
    {% load static %}
    {% block header %}

    {% endblock %}

    <style>
      @keyframes payload_blink {
        from {
          background-color: #ffffff;
        }
        to {
          background-color: #bef3be;
        }
      }

      p {
        font-size: 70%;
        margin-bottom: 7px;
      }

      h5 {
        font-size: 90%;
        margin-bottom: 10px;
      }
    </style>

  </head>
  <body>
    {% block fixedtopbar %}

    {% endblock %}
    <div class="container" style="margin-top:75px">

      {% if user.is_authenticated %}
        <!-- Lista de tipos de dispositivos e seus dispositivos correspondentes -->
        {% for device_type in device_type_list %}
          <div class="alert alert-dark font-weight-bold" style="margin-top:15px">{{ device_type.0.desc }}:</div>

          <div class="row text-center" style="padding-top:0px; padding-left:10px; padding-right:10px; padding-bottom:10px">
            {% for device in device_list %}
              {% if device.0.device_type.type_id == device_type.0.type_id and device.0.device_type.type_id == 1 %}
                  {% include "argos/monitor1.html" %}
              {% endif %}
              {% if device.0.device_type.type_id == device_type.0.type_id and device.0.device_type.type_id == 2 %}
                  {% include "argos/monitor2.html" %}
              {% endif %}
              {% if device.0.device_type.type_id == device_type.0.type_id and device.0.device_type.type_id == 3 %}
                  {% include "argos/monitor3.html" %}
              {% endif %}
              {% if device.0.device_type.type_id == device_type.0.type_id and device.0.device_type.type_id == 4 %}
                  {% include "argos/monitor4.html" %}
              {% endif %}
              {% if device.0.device_type.type_id == device_type.0.type_id and device.0.device_type.type_id == 5 %}
                  {% include "argos/monitor5.html" %}
              {% endif %}
            {% endfor %}
          </div>
        {% endfor %}

      {% else %}
        <div class="alert alert-danger">Você não tem permissão para acessar esta página.</div>
      {% endif %}

      <p hidden id="is_admin">{{ is_admin }}</p>

    </div>

    {% block fixedbottombar %}
    <!-- Aqui o template pode ser sobrescrito para incluir um fixedbottom bar diferente -->
    {% endblock %}

    <script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/crossfilter.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/d3.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/dc.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/argos.dc.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/argos.js' %}"></script>

    <script>
      //formata configurações regionais
      formatLocale();

      //objeto json com dados do dispositivo
      var devJson = {{ device_json|safe }};

      //cria uma conexão por websocket com o django channels
      var webSocketArgos = new WebSocket('ws://' + window.location.host + '/ws/argos/');

      /*
      O bloco a seguir foi comentado pois a Mauá desabilitará a REST API. Se obter
      o último dado enviado for realmente importante, deverá ser implementada uma
      REST API no servidor do Argos, uma vez que deveremos trabalhar sempre com
      data_mode = 'local'
      //listas de http resquests e http responses
      var httpRequest = [];
      var httpResponse =[];
      //varre lista de dispositivos
      for(i = 0; i < devJson.length; i++) {
        //cria um http request
        httpRequest[i] = new XMLHttpRequest();
        //atribui um índice ao http request
        httpRequest[i].ind = i;
        //realiza as requisições http, conforme servidor do dispositivo
        if (devJson[i]['server'] == 3) {
          //requisição ao servidor Mauá (argumento true é para assíncrono e é o default)
          httpRequest[i].open('GET','https://smartcampus.maua.br/api/index.php/' + devJson[i]['pwd'] + '/1/' + devJson[i]['eui'], true);
        }

        //define a função de callback do http request
        httpRequest[i].onreadystatechange = function() {
          if (this.readyState == 4 && this.status == 200) {
            httpReady(this.ind);
          }
        }
        //realiza a requisição
        httpRequest[i].send();
      }
      */
      //função onclose
      webSocketArgos.onclose = function(e) {
        console.error('Websocket closed unexpectedly.');
      };

      //define função que deverá ser chamada toda vez que chegar uma mensagem
      webSocketArgos.onmessage = function(e) {
        var payload;
        var data = JSON.parse(e.data);

        /*
        O bloco a seguir foi comentado pois a Mauá desabilitará a REST API. Se obter
        o último dado enviado for realmente importante, deverá ser implementada uma
        REST API no servidor do Argos, uma vez que deveremos trabalhar sempre com
        data_mode = 'local'
        //varre lista de dispositivos
        for(i = 0; i < devJson.length; i++) {
          //busca dispositivo referente ao pacote que acabou de chegar
          if (devJson[i]['eui'] == data['message']['eui']) {
            //indica que a atualização via http request não é mais necessária
            devJson[i]['enabled'] = false;
          }
        }
        */
        //preenche elementos html com dados do objeto
        if (data['message']['logs'].length > 0) {
          //sensor de tensão e corrente
          if (data['message']['device_type'] == 1) {
            printDataMonitor1(data['message']);
            blinkIt(data['message']['eui'], 6);
          }
          //remota para medidor de energia
          else if (data['message']['device_type'] == 2) {
            printDataMonitor2(data['message']);
            blinkIt(data['message']['eui'], 6);
          }
          //rastreador GPS
          else if (data['message']['device_type'] == 4) {
            printDataMonitor4(data['message']);
            blinkIt(data['message']['eui'], 6);
          }
          //sensor de temperatura e umidade
          else if (data['message']['device_type'] == 5) {
            printDataMonitor5(data['message']);
            blinkIt(data['message']['eui'], 6);
          }
        }
      };

      //função onopen faz a subscrição no mqtt
      webSocketArgos.onopen = function(event) {
        var payload;
        devJson.forEach(function (obj) {
          webSocketArgos.send(JSON.stringify({
            'message': {'type': 'subscribe', 'log': obj}
          }));
        })
      };

      //função de efeito visual para piscar um monitor quando houver atualização de dados
      function blinkIt(device_eui, times) {
        var id = 'monitor_' + device_eui.toUpperCase();
        //numeroVezesSTR = String(numeroVezes)
        //reseta animação
        document.getElementById(id).style.animationName = 'none';
        //faz piscar por algum tempo o monitor que foi atualizado
        setTimeout(function() {
          document.getElementById(id).style.animationName = 'payload_blink';
          document.getElementById(id).style.animationDuration = '0.6s';
          document.getElementById(id).style.animationIterationCount = times;
          document.getElementById(id).style.animationDirection = 'alternate';
        }, 150)
      }

      /*
      O bloco a seguir foi comentado pois a Mauá desabilitará a REST API. Se obter
      o último dado enviado for realmente importante, deverá ser implementada uma
      REST API no servidor do Argos, uma vez que deveremos trabalhar sempre com
      data_mode = 'local'
      //função chamada quando o http request dá retorno
      function httpReady(ind) {
        var data = {};
        //se dispositivo recebeu pacote via mqtt antes de chegar a resposta
        //do http request, finaliza a execução da função
        if (devJson[ind]['enabled'] == false) return;
        //transforma a resposta da requisição de texto para JSON
        httpResponse[ind] = JSON.parse(httpRequest[ind].responseText);
        //arruma o JSON para o formato adequado das funções do argos, conforme o servidor
        if (devJson[ind]['server'] == 3) {
          //especifica formatadores de data
          var pt = d3.timeParse('%Y-%m-%d %H:%M:%S.%f%Z');
          var ft = d3.timeFormat('%d/%m/%Y %H:%M:%S.%f');
          //requisição ao servidor Mauá (argumento true é para assíncrono e é o default)
          data['message'] = {};
          data['message']['data_format'] = devJson[ind]['rest_data_format'];
          data['message']['eui'] = devJson[ind]['eui'];
          data['message']['device_type'] = devJson[ind]['device_type'];
          data['message']['server'] = devJson[ind]['server'];
          data['message']['logs'] = [];
          data['message']['logs'].push({
            'datetime_rx': ft(pt(httpResponse[ind]['logs'][0]['created_at'])),
            'data_payload': httpResponse[ind]['logs'][0]['data_payload']
          });
        }

        //sensor de tensão e corrente
        if (data['message']['device_type'] == 1) {
          //nada a fazer por enquanto
        }
        //remota para medidor de energia
        else if (data['message']['device_type'] == 2) {
          printDataMonitor2(data['message']);
          blinkIt(data['message']['eui'], 2);
        }
        //sensor de temperatura
        else if (data['message']['device_type'] == 3) {
          //nada a fazer por enquanto
        }
        //rastreador GPS
        else if (data['message']['device_type'] == 4) {
          printDataMonitor4(data['message']);
          blinkIt(data['message']['eui'], 2);
        }
        //sensor de temperatura e umidade
        else if (data['message']['device_type'] == 5) {
          printDataMonitor5(data['message']);
          blinkIt(data['message']['eui'], 2);
        }
      }
      */
      //função para desligar uma remota
      function turnOff(eui) {
        var commandJson = {
          'message': {
            'type': 'publish', 'log': {
              'eui': eui.toLowerCase(),
              'server': document.getElementById('server_' + eui).innerHTML,
              'command': {
                'reference': 'test-node-red',
                'confirmed': false,
                'fPort': 100,
                'data': 'AAQ='
              }
            }
          }
        };
        webSocketArgos.send(JSON.stringify(commandJson));
        document.getElementById('turnOff_' + eui).disabled = true;
      }

      //função para ligar uma remota
      function turnOn(eui) {
        var commandJson = {
          'message': {
            'type': 'publish', 'log': {
              'eui': eui.toLowerCase(),
              'server': document.getElementById('server_' + eui).innerHTML,
              'command': {
                'reference': 'test-node-red',
                'confirmed': false,
                'fPort': 100,
                'data': 'AAg='
              }
            }
          }
        };
        webSocketArgos.send(JSON.stringify(commandJson));
        document.getElementById('turnOn_' + eui).disabled = true;
      }

      resetScrollTop();

    </script>
  </body>
</html>

argos/templates/argos/detail6inner.html
<!doctype html>
<html lang="pt-BR">
  <head>
    {% load static %}
    {% block header %}

    {% endblock %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/dc.css' %}">
  </head>
  <body>
    {% block fixedtopbar %}

    {% endblock %}

    <div class="container-fluid" style="margin-top:80px">

      {% if user.is_authenticated %}

      <div class="row">

        <!-- Barra de pesquisa e barra de navegação -->
        {% include "argos/navsidebar.html" %}

        <!-- Painel de navegação principal -->
        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">

          <div class="alert alert-dark font-weight-bold">Gráficos - {{ device.desc }} ({{ device.eui }})</div>

          <!-- Abas dos gráficos -->
          <ul class="nav nav-tabs">
            
              <li class="nav-item">
              <a class="nav-link active" data-toggle="tab" href="#chart1">Corrente</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" data-toggle="tab" href="#chart2">Bateria e Tempo</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" data-toggle="tab" href="#chart3">SNR e RSSI</a>
            </li>
          </ul>

          <!-- Gráficos das diferentes abas -->
          <div class="tab-content">
            <div class="container tab-pane active" id="chart1">
              <div class="row">
                <div class="container" id="myChart1"></div>
              </div>
              <div class="row">
                <div class="container" id="myRangeChart1"></div>
              </div>
            </div>
            <div class="container tab-pane fade" id="chart2">
              <div class="row">
                <div class="container" id="myChart2"></div>
              </div>
              <div class="row">
                <div class="container" id="myRangeChart2"></div>
              </div>
            </div>
            <div class="container tab-pane fade" id="chart3">
              <div class="row">
                <div class="container" id="myChart3"></div>
              </div>
              <div class="row">
                <div class="container" id="myRangeChart3"></div>
              </div>
            </div>
          </div>

          {% include "argos/formperiod.html" %}

          <div class="alert alert-dark font-weight-bold" style="margin-top:30px">Tabelas de dados - {{ device.desc }} ({{ device.eui }})</div>

          <!-- Abas das tabelas -->
          <ul class="nav nav-tabs">
            <li class="nav-item">
              <a class="nav-link active" data-toggle="tab" href="#table1">Correntes</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" data-toggle="tab" href="#table2">Detecção de Tensão</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" data-toggle="tab" href="#table3">Bateria</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" data-toggle="tab" href="#table4">Informações dos Pacotes</a>
            </li>
          </ul>

          <!-- Tabelas das diferentes abas -->
          <div class="tab-content">
            <div class="container tab-pane active" id="table1">
              <div class="table-responsive">
                <table class="table table-striped table-sm" id="myTable1" style="font-size:85%">
                  <thead>
                    <tr>
                      <th scope="col">Data/Horário</th>
                      <th scope="col">Corrente Fusível 1 [A]</th>
                      <th scope="col">Corrente Fusível 2 [A]</th>
                      <th scope="col">Corrente Fusível 3 [A]</th>
                    </tr>
                  </thead>
                </table>
              </div>
            </div>
            <div class="container tab-pane fade" id="table2">
              <div class="table-responsive">
                <table class="table table-striped table-sm" id="myTable2" style="font-size:85%">
                  <thead>
                    <tr>
                      <th scope="col">Data/Horário</th>
                      <th scope="col">Valor do Sensor</th>
                      <th scope="col">Indicador de Tensão</th>
                    </tr>
                  </thead>
                </table>
              </div>
            </div>
            <div class="container tab-pane fade" id="table3">
              <div class="table-responsive">
                <table class="table table-striped table-sm" id="myTable3" style="font-size:85%">
                  <thead>
                    <tr>
                      <th scope="col">Data/Horário</th>
                      <th scope="col">Nível da Bateria [V]</th>
                    </tr>
                  </thead>
                </table>
              </div>
            </div>
            <div class="container tab-pane fade" id="table4">
              <div class="table-responsive">
                <table class="table table-striped table-sm" id="myTable4" style="font-size:85%">
                  <thead>
                    <tr>
                      <th scope="col">Data/Horário</th>
                      <th scope="col">Payload</th>
                      <th scope="col">Intervalo [min]</th>
                      <th scope="col">SNR</th>
                      <th scope="col">RSSI [dbi]</th>
                    </tr>
                  </thead>
                </table>
              </div>
            </div>
          </div>

          <!-- Controles de paginação -->
          <div style="padding-bottom: 20px">
            <input id="id_previous" class="btn btn-secondary" type="button" value="<" />
            <input id="id_next" class="btn btn-secondary" type="button" value=">" />
            <input id="id_export" class="btn btn-secondary" type="button" value="Exportar Dados" />
          </div>

          {% block fixedbottombar %}
          <!-- Aqui o template pode ser sobrescrito para incluir um fixedbottom bar diferente -->
          {% endblock %}

        </main>
      </div>

      {% else %}
        <div class="alert alert-danger">Você não tem permissão para acessar esta página.</div>
      {% endif %}
    </div>

    <script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/crossfilter.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/d3.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/dc.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/argos.dc.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/argos.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/download.js' %}"></script>

    <script>
      //inicia dropdown
      initDropdown();
      /*
      O bloco a seguir monta o gráfico e a tabela.
      */
      //formata configurações regionais (função original)
      formatLocale();
      //objeto json com dados
      var valuesJson = {{ values|safe }};
      //prepara dados
      valuesJson.forEach(function(d) {
        d.datetime_rx = parseTime(d.datetime_rx);
      });
      //preenche e exibe gráfico e tabela (ver argos.dc.js)
      dcChartTable6(valuesJson, "#myChart1", "#myChart2", "#myChart3",
                                "#myRangeChart1", "#myRangeChart2", "#myRangeChart3",
                                "#myTable1", "#myTable2", "#myTable3", "#myTable4");

      getSetScrollTop();
    </script>
  </body>
</html>

argos/templates/argos/whitetarifflistinner.html
<!doctype html>
<html lang="pt-BR">
  <head>
    {% load static %}
    {% block header %}

    {% endblock %}
  </head>
  <body>
    {% block fixedtopbar %}

    {% endblock %}

    <!-- Barra de pesquisa -->
    <div class="container bg-white" style="margin-top:75px" id="navSearch">
      <form class="navbar-form navbar-shadow" >
        <div class="input-group">
          <input type="search" class="form-control" placeholder="Pesquisar..." oninput="filterTables()" id="inputSearch">
          <!--
          <div class="input-group-btn">
            <button class="btn btn-secondary" type="button" onclick="filterTables()" id="butSearch">
              <i class="fas fa-search"></i>
            </button>
          </div>
          -->
        </div>
      </form>
    </div>

    <div class="container" style="margin-top:25px">

      {% if user.is_authenticated %}

        <div class="alert alert-dark font-weight-bold">Instalações:</div>

        <!-- Lista de instalações -->
        <div class="table-responsive">
          <table class="table table-striped table-sm" style="font-size:85%">
            <thead>
              <tr>
                <th scope="col">Instalação</th>
                <th scope="col">Medidor</th>
                <th scope="col">MAC do medidor</th>
                <th scope="col">Data inicial</th>
                <th scope="col">Data final</th>
              </tr>
            </thead>
            <tbody>
              {% for installation_meter in installations_meters %}
                <tr>
                  <td>{{ installation_meter.installation.code }}</td>
                  <td><a href="{% url 'argos:whitetariff' installation_meter.meter.mac %}">{{ installation_meter.meter.desc }}</a></td>
                  <td>{{ installation_meter.meter.mac }}</td>
                  <td>{{ installation_meter.date_ini }}</td>
                  <td>{{ installation_meter.date_fin }}</td>
                </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>

        <div class="alert alert-dark font-weight-bold">Medidores:</div>

        <!-- Lista de medidores -->
        <div class="table-responsive">
          <table class="table table-striped table-sm" style="font-size:85%">
            <thead>
              <tr>
                <th scope="col">Descrição</th>
                <th scope="col">MAC</th>
                <th scope="col">Servidor</th>
              </tr>
            </thead>
            <tbody>
              {% for meter in meters %}
                <tr>
                  <td><a href="{% url 'argos:whitetariff' meter.mac %}">{{ meter.desc }}</a></td>
                  <td>{{ meter.mac }}</td>
                  <td>{{ meter.server.desc }}</td>
                </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>

      {% else %}
        <div class="alert alert-danger">Você não tem permissão para acessar esta página.</div>
      {% endif %}

    </div>

    {% block fixedbottombar %}
    <!-- Aqui o template pode ser sobrescrito para incluir um fixedbottom bar diferente -->
    {% endblock %}

    <script type="text/javascript" src="{% static 'js/argos.js' %}"></script>

    <script>
      resetScrollTop();
    </script>

  </body>
</html>

argos/templates/argos/whitetariffsidebar.html
<nav class="navbar navbar-shadow col-md-2 d-none d-md-block bg-light" style="height=8%;position:fixed;overflow:auto" id="navMenu2">
  <ul class="nav navbar-nav">
    <div>
      <label class="control-label mr-sm-2" style="font-size:85%">Filtro de medições</label>
    </div>
    <form class="form-inline" method="post" action="{% url 'argos:whitetariff' meter.mac %}">
      {% csrf_token %}
      <div class="form-group" style="margin-top:1px">
        <label class="control-label mr-sm-2" style="font-size:70%">Data inicial:</label>
      </div>
      <div class="form-group" style="margin-top:3px">
        <input type="datetime-local" class="form-control mb-2 mr-sm-2" onChange="updateHiddenFields()" style="font-size:70%" size="10" id="datetime_ini" name="datetime_ini" min="{{ datetime_ini_min }}" max="{{ datetime_fin_max }}" value="{{ datetime_ini }}" />
      </div>
      <div class="form-group" style="margin-top:3px">
        <label class="control-label mr-sm-2" style="font-size:70%">Data final:</label>
      </div>
      <div class="form-group" style="margin-top:3px">
        <input type="datetime-local" class="form-control mb-2 mr-sm-2" onChange="updateHiddenFields()" style="font-size:70%" size="10" id="datetime_fin" name="datetime_fin" min="{{ datetime_ini_min }}" max="{{ datetime_fin_max }}" value="{{ datetime_fin }}" />
      </div>
      <!-- Campos ocultos, apenas para replicar os filtros específicos (dias da semana e estações do ano) -->
      <div>
        <input hidden class="form-check-input" type="checkbox" value="alldays" id="ckAlldays_hidden" name="ckWeekday_hidden" checked>
        <input hidden class="form-check-input" type="checkbox" value="monday" id="ck2af_hidden" name="ckWeekday_hidden" checked>
        <input hidden class="form-check-input" type="checkbox" value="tuesday" id="ck3af_hidden" name="ckWeekday_hidden" checked>
        <input hidden class="form-check-input" type="checkbox" value="wednesday" id="ck4af_hidden" name="ckWeekday_hidden" checked>
        <input hidden class="form-check-input" type="checkbox" value="thursday" id="ck5af_hidden" name="ckWeekday_hidden" checked>
        <input hidden class="form-check-input" type="checkbox" value="friday" id="ck6af_hidden" name="ckWeekday_hidden" checked>
        <input hidden class="form-check-input" type="checkbox" value="saturday" id="ckSab_hidden" name="ckWeekday_hidden" checked>
        <input hidden class="form-check-input" type="checkbox" value="sunday" id="ckDom_hidden" name="ckWeekday_hidden" checked>
        <input hidden class="form-check-input" type="checkbox" value="allSeasons_hidden" id="ckAllSeasons_hidden" name="ckSeason_hidden" checked>
        <input hidden class="form-check-input" type="checkbox" value="summer" id="ckSummer_hidden" name="ckSeason_hidden" checked>
        <input hidden class="form-check-input" type="checkbox" value="fall" id="ckFall_hidden" name="ckSeason_hidden" checked>
        <input hidden class="form-check-input" type="checkbox" value="winter" id="ckWinter_hidden" name="ckSeason_hidden" checked>
        <input hidden class="form-check-input" type="checkbox" value="spring" id="ckSpring_hidden" name="ckSeason_hidden" checked>
      </div>
      <div class="form-group" style="margin-top:3px">
        <input type="submit" class="btn btn-secondary mb-2" style="font-size:70%" value="Atualizar" />
      </div>
    </form>
  </ul>
</nav>
<!-- Barra de pesquisa -->
<nav class="navbar navbar-shadow col-md-2 d-none d-md-block bg-light" style="position:fixed;margin-top:215px;padding:0" id="navSearch">
  <form class="navbar-form navbar-left">
    <div class="input-gro up">
      <input type="search" class="form-control" placeholder="Pesquisar..." oninput="filterContent()" id="inputSearch">
      <!--
      <div class="input-group-btn">
        <button class="btn btn-secondary" type="button" onclick="filterContent()" id="butSearch">
          <i class="fas fa-search"></i>
        </button>
      </div>
      -->
    </div>
  </form>
</nav>
<!-- Barra de navegação -->
<nav class="navbar navbar-shadow col-md-2 d-none d-md-block bg-light" style="height:78%;position:fixed;margin-top:260px;overflow:auto" id="navMenu">
  <ul class="nav navbar-nav">
    <li class="dropdown show">
      <!-- Lista de instalações -->
      <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#">Instalações</a>
      <div class="dropdown-menu show bg-light" style="border-style:none">
        {% for installation_meter in installations_meters %}
        <a class="dropdown-item" style="font-size:85%" href="{% url 'argos:whitetariff' installation_meter.meter.mac %}">{{ installation_meter.installation.code }} ({{ installation_meter.meter.desc }})</a>
        {% endfor %}
      </div>
    </li>
    <li class="dropdown show">
      <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#">Medidores</a>
      <div class="dropdown-menu show bg-light" style="border-style:none">
        {% for meter in meters_list %}
        <a class="dropdown-item" style="font-size:85%" href="{% url 'argos:whitetariff' meter.mac %}">{{ meter.desc }}</a>
        {% endfor %}
      </div>
    </li>
  </ul>
</nav>